project:
  type: website

website:
  title: "Summer Data Science Practicum"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: lectures.qmd
        text: Lectures

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

