project:
  type: website

website:
  title: "Summer Data Science Practicum"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: getting-started.qmd
        text: "Getting started"
      - href: syllabus.qmd
        text: Syllabus
      - href: lectures.qmd
        text: Lectures

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

