---
title: "Getting started"
---

Welcome the summer Data Science Practicum at Gordon College! This website provides information and resources related to the lecture portion of the practicum.

## Syllabus

### Learning outcomes

At the end of the lecture portion of the practicum, students will be able to:

1.  Identify all steps in the general data science workflow, and describe the utility of each step using examples.
2.  Apply the six fundamental transformation verbs (used in the `{dplyr}` API) to perform wrangling tasks.
3.  

### Lecture schedule

The lecture schedule for summer 2023. Morning sessions run from 9:00am to 12:00pm, and afternoon sessions from 1:00pm to 4:00pm

| Date                 | Session   | Topic                                |
|----------------------|-----------|--------------------------------------|
| Tuesday, May 30th    | Morning   | Up and running with R and RStudio    |
| Tuesday, May 30th    | Afternoon | Creating generative art              |
| Wednesday, May 31st  | Morning   | Basic data structures in R           |
| Wednesday, May 31st  | Afternoon | Tibbles and the tidyverse            |
| Thursday, June 1st   | Morning   | The data science workflow            |
| Thursday, June 1st   | Afternoon | First steps in exploratory plotting  |
| Friday, June 2nd     | Morning   | Transforming rectangular data        |
| Friday, June 2nd     | Afternoon | Case study: what makes a hero super? |
| Monday, June 5th     | Morning   | Data science with ChatGPT            |
| Monday, June 5th     | Afternoon | Writing your own functions           |
| Tuesday, June 6th    | Morning   | B.Y.O.D (bring your own data)        |
| Tuesday, June 6th    | Afternoon | Common cleaning tasks                |
| Wednesday, June 7th  | Morning   | Tidy data and reshaping              |
| Wednesday, June 7th  | Afternoon | Using iteration for automation       |
| Thursday, June 8th   | Morning   | Basic functional programming         |
| Thursday, June 8th   | Afternoon | The grammar of graphics              |
| Friday, June 9th     | Morning   | Plots that speak clearly             |
| Friday, June 9th     | Afternoon | Case study:                          |
| Monday, June 12th    | Morning   | Working with dates and times         |
| Monday, June 12th    | Afternoon | Case study:                          |
| Tuesday, June 13th   | Morning   | Working with strings                 |
| Tuesday, June 13th   | Afternoon | Case study:                          |
| Wednesday, June 14th | Morning   | Working with spatial data            |
| Wednesday, June 14th | Afternoon | Case study: mapping UFO sightings    |
| Thursday, June 15th  | Morning   |                                      |
| Thursday, June 15th  | Afternoon |                                      |
| Friday, June 16th    | Morning   |                                      |
| Friday, June 16th    | Afternoon |                                      |
