---
title: "Lectures"
slide-format: revealjs
---

::: callout-note
All lectures are available at <http://mason.quarto.pub>. Lecture titles are hyperlinks to the original slides with a fullscreen viewing option.
:::

## Lecture 1: [Up and running with R and RStudio](https://mason.quarto.pub/up-and-running-with-r-and-rstudio/#/title-slide)

```{=html}
<iframe class="slide-deck" src="https://mason.quarto.pub/up-and-running-with-r-and-rstudio/" title="Up and running with R and Studio"></iframe>
```
::: {.callout-important title="Reading Assignment" icon="false" collapse="true" appearance="simple"}
-   [R for Data Science Chapter 4 - Workflow: basics](https://r4ds.had.co.nz/workflow-basics.html)
-   [R for Data Science Chapter 6 - Workflow: scripts](https://r4ds.had.co.nz/workflow-scripts.html)
:::

::: {.callout-tip title="DataCamp Assignment" icon="false" collapse="true" appearance="simple"}
-   Introduction to R: Intro to basics
-   Introduction to R: Vectors
:::

## Lecture 2: [Using functions to create generative art](https://mason.quarto.pub/using-functions-to-create-generative-art/)

```{=html}
<iframe class="slide-deck" src="https://mason.quarto.pub/using-functions-to-create-generative-art/" title="Using functions to create generative art"></iframe>
```
## Lecture 3: [Basic data structures in R](https://mason.quarto.pub/basic-data-structures-in-r/)

```{=html}
<iframe class="slide-deck" src="https://mason.quarto.pub/basic-data-structures-in-r/" title="Basic data structures in R"></iframe>
```
::: {.callout-tip title="DataCamp Assignment" icon="false" collapse="true" appearance="simple"}
-   Introduction to R: Matrices
-   Introduction to R: Factors
-   Introduction to R: Data frames
-   Introduction to R: Lists
:::

## Lecture 4: [Tibbles and the tidyverse](https://mason.quarto.pub/tibbles-and-the-tidyverse/)

```{=html}
<iframe class="slide-deck" src="https://mason.quarto.pub/tibbles-and-the-tidyverse/" title="Tibbles and the tidyverse"></iframe>
```
::: {.callout-important title="Reading Assignment" icon="false" collapse="true" appearance="simple"}
-   [R for Data Science Chapter 10 - Tibbles](https://r4ds.had.co.nz/tibbles.html)
:::

## Lecture 5: The data science workflow

## Lecture 6: [First steps in exploratory plotting](https://mason.quarto.pub/first-steps-in-exploratory-plotting/)

```{=html}
<iframe class="slide-deck" src="https://mason.quarto.pub/first-steps-in-exploratory-plotting/" title="First steps in exploratory plotting"></iframe>
```
::: {.callout-important title="Reading Assignment" icon="false" collapse="true" appearance="simple"}
-   [R for Data Science Chapter 3 - Introduction](https://r4ds.had.co.nz/data-visualisation.html#introduction-1)
-   [R for Data Science Chapter 3 - First steps](https://r4ds.had.co.nz/data-visualisation.html#first-steps)
-   [R for Data Science Chapter 3 - Aesthetic mappings](https://r4ds.had.co.nz/data-visualisation.html#aesthetic-mappings)
-   [R for Data Science Chapter 3 - Common problems](https://r4ds.had.co.nz/data-visualisation.html#common-problems)
-   [R for Data Science Chapter 3 - Geometric objects](https://r4ds.had.co.nz/data-visualisation.html#geometric-objects)
:::

::: {.callout-tip title="DataCamp Assignment" icon="false" collapse="true" appearance="simple"}
-   Introduction to data visualization with ggplot2: Introduction
-   Introduction to data visualization with ggplot2: Aesthetics
-   Introduction to data visualization with ggplot2: Geometries
:::

## Lecture 7: [Transforming rectangular data](https://mason.quarto.pub/transforming-rectangular-data/)

```{=html}
<iframe class="slide-deck" src="https://mason.quarto.pub/transforming-rectangular-data/" title="Transforming rectangular data"></iframe>
```
::: {.callout-important title="Reading Assignment" icon="false" collapse="true" appearance="simple"}
-   [R for Data Science Chapter 5 - Introduction](https://r4ds.had.co.nz/transform.html#introduction-2)
-   [R for Data Science Chapter 5 - Filter](https://r4ds.had.co.nz/transform.html#filter-rows-with-filter)
-   [R for Data Science Chapter 5 - Arrange](https://r4ds.had.co.nz/transform.html#arrange-rows-with-arrange)
-   [R for Data Science Chapter 5 - Select](https://r4ds.had.co.nz/transform.html#select)
-   [R for Data Science Chapter 5 - Mutate](https://r4ds.had.co.nz/transform.html#add-new-variables-with-mutate)
-   [R for Data Science Chapter 5 - Grouped summaries](https://r4ds.had.co.nz/transform.html#grouped-summaries-with-summarise)
:::

::: {.callout-tip title="DataCamp Assignment" icon="false" collapse="true" appearance="simple"}
-   Data manipulation with dplyr: transforming data with dplyr
-   Data manipulation with dplyr: aggregating data
-   Data manipulation with dplyr: selecting and transforming data
-   Data manipulation with dplyr: case study: the babynames dataset
:::

## Lecture 8: [Writing your own functions](https://mason.quarto.pub/writing-your-own-functions/)

```{=html}
<iframe class="slide-deck" src="https://mason.quarto.pub/writing-your-own-functions/" title="Writing your own functions"></iframe>
```

::: {.callout-important title="Reading Assignment" icon="false" collapse="true" appearance="simple"}
-   [R for Data Science Chapter 19 - Introduction](https://r4ds.had.co.nz/functions.html#introduction-12)
-   [R for Data Science Chapter 19 - When to write functions](https://r4ds.had.co.nz/functions.html#when-should-you-write-a-function)
-   [R for Data Science Chapter 19 - Naming functions](https://r4ds.had.co.nz/functions.html#functions-are-for-humans-and-computers)
-   [R for Data Science Chapter 19 - Conditional execution](https://r4ds.had.co.nz/functions.html#conditional-execution)
-   [R for Data Science Chapter 19 - Naming arguments](https://r4ds.had.co.nz/functions.html#choosing-names)
-   [R for Data Science Chapter 19 - Checking values](https://r4ds.had.co.nz/functions.html#checking-values)
:::

::: {.callout-tip title="DataCamp Assignment" icon="false" collapse="true" appearance="simple"}
-   Intermediate R: conditionals and control flow
-   Intermediate R: functions
:::

## Lecture 9: [B.Y.O.D. (bring your own data)](https://mason.quarto.pub/byod-(bring-your-own-data/)

```{=html}
<iframe class="slide-deck" src="https://mason.quarto.pub/byod-(bring-your-own-data/" title="B.Y.O.D. (bring your own data)"></iframe>
```
